version: '3'

# Catalog CUE Modules Taskfile
# Self-contained tasks for catalog/v0/* modules (multi-module aware)
#
# This Taskfile can be run standalone from the catalog/ directory:
#   cd catalog && task fmt
#   cd catalog && task fmt MODULE=schemas
#   cd catalog && task version
#   cd catalog && task publish:local MODULE=schemas
#   cd catalog && task publish:all:local
#
# Or via root orchestration:
#   task module:fmt MODULE=schemas

silent: true

vars:
  V0_DIR: v0
  LOCAL_REGISTRY: localhost:5000
  VERSION_FILE: versions.yml
  
  # Catalog modules in dependency order
  CATALOG_MODULES:
    - name: core
      path: core
      enabled: true
      desc: "Core OPM definitions (no deps)"

    - name: schemas
      path: schemas
      enabled: true
      desc: "Shared schemas (no deps)"

    - name: resources
      path: resources
      enabled: true
      desc: "Resource implementations"

    - name: traits
      path: traits
      enabled: true
      desc: "Trait implementations"

    - name: blueprints
      path: blueprints
      enabled: false
      desc: "Blueprint implementations"

    - name: policies
      path: policies
      enabled: true
      desc: "Policy implementations"

    - name: providers
      path: providers
      enabled: true
      desc: "Provider implementations"

    - name: examples
      path: examples
      enabled: true
      desc: "Example implementations"

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  # ============================================================================
  # Formatting
  # ============================================================================

  fmt:
    desc: Format CUE files (all modules or specific MODULE)
    summary: |
      Format CUE files in catalog modules.

      Usage:
        task fmt              # Format all modules
        task fmt MODULE=schemas  # Format specific module
    vars:
      MODULE: '{{.MODULE | default ""}}'
    cmds:
      - |
        if [ -n "{{.MODULE}}" ]; then
          echo "Formatting {{.MODULE}}..."
          cd "{{.V0_DIR}}/{{.MODULE}}" && cue fmt ./...
          echo "Done"
        else
          echo "Formatting all catalog modules..."
          {{range $mod := .CATALOG_MODULES}}{{if $mod.enabled}}
          echo "  Formatting {{$mod.name}}..."
          (cd "{{$.V0_DIR}}/{{$mod.path}}" && cue fmt ./...) || true
          {{end}}{{end}}
          echo "Done"
        fi

  # ============================================================================
  # Validation
  # ============================================================================

  vet:
    desc: Validate CUE files (all modules or specific MODULE)
    summary: |
      Validate CUE files in catalog modules.

      Usage:
        task vet              # Validate all modules
        task vet MODULE=schemas  # Validate specific module
    vars:
      MODULE: '{{.MODULE | default ""}}'
    cmds:
      - |
        if [ -n "{{.MODULE}}" ]; then
          echo "Validating {{.MODULE}}..."
          cd "{{.V0_DIR}}/{{.MODULE}}" && cue vet ./...
          echo "Done"
        else
          echo "Validating all catalog modules..."
          FAILED=""
          {{range $mod := .CATALOG_MODULES}}{{if $mod.enabled}}
          echo "  Validating {{$mod.name}}..."
          if ! (cd "{{$.V0_DIR}}/{{$mod.path}}" && cue vet ./... 2>&1); then
            FAILED="${FAILED} {{$mod.name}}"
          fi
          {{end}}{{end}}
          
          if [ -n "$FAILED" ]; then
            echo ""
            echo "Failed:${FAILED}"
            exit 1
          fi
          echo "Done"
        fi

  # ============================================================================
  # Module Management
  # ============================================================================

  tidy:
    desc: Tidy module dependencies (all modules or specific MODULE)
    vars:
      MODULE: '{{.MODULE | default ""}}'
    cmds:
      - |
        if [ -n "{{.MODULE}}" ]; then
          echo "Tidying {{.MODULE}} dependencies..."
          cd "{{.V0_DIR}}/{{.MODULE}}" && CUE_REGISTRY={{.LOCAL_REGISTRY}}+insecure cue mod tidy
          echo "Done"
        else
          echo "Tidying all catalog module dependencies..."
          {{range $mod := .CATALOG_MODULES}}{{if $mod.enabled}}
          echo "  Tidying {{$mod.name}}..."
          (cd "{{$.V0_DIR}}/{{$mod.path}}" && CUE_REGISTRY={{$.LOCAL_REGISTRY}}+insecure cue mod tidy) || true
          {{end}}{{end}}
          echo "Done"
        fi

  # ============================================================================
  # Watch Mode
  # ============================================================================

  watch:fmt:
    desc: Watch and auto-format on changes
    preconditions:
      - sh: command -v watchexec
        msg: "watchexec is required. Install: brew install watchexec"
    cmds:
      - |
        echo "Watching catalog modules for changes..."
        echo "Press Ctrl+C to stop"
        cd "{{.V0_DIR}}" && watchexec -e cue -- bash -c '
          {{range $mod := .CATALOG_MODULES}}{{if $mod.enabled}}
          (cd "{{$mod.path}}" && cue fmt ./...) || true
          {{end}}{{end}}
          echo "Formatted"
        '

  watch:vet:
    desc: Watch and auto-validate on changes
    preconditions:
      - sh: command -v watchexec
        msg: "watchexec is required. Install: brew install watchexec"
    cmds:
      - |
        echo "Watching catalog modules for changes..."
        echo "Press Ctrl+C to stop"
        cd "{{.V0_DIR}}" && watchexec -e cue -- bash -c '
          FAILED=""
          {{range $mod := .CATALOG_MODULES}}{{if $mod.enabled}}
          if ! (cd "{{$mod.path}}" && cue vet ./... 2>&1); then
            FAILED="${FAILED} {{$mod.name}}"
          fi
          {{end}}{{end}}
          if [ -n "$FAILED" ]; then
            echo "Failed:${FAILED}"
          else
            echo "All valid"
          fi
        '

  # ============================================================================
  # Combined Operations
  # ============================================================================

  check:
    desc: Run fmt and vet on all modules
    cmds:
      - task fmt
      - task vet

  # ============================================================================
  # Module Info
  # ============================================================================

  list:
    desc: List all catalog modules
    cmds:
      - |
        echo "Catalog Modules:"
        {{range $mod := .CATALOG_MODULES}}
        {{if $mod.enabled}}
        echo "  {{$mod.name}}: {{$mod.desc}}"
        {{else}}
        echo "  {{$mod.name}}: {{$mod.desc}} (disabled)"
        {{end}}
        {{end}}

  # ============================================================================
  # Version Management
  # ============================================================================

  version:
    desc: Show module versions (all or specific MODULE)
    summary: |
      Display versions for catalog modules.

      Usage:
        task version              # Show all module versions
        task version MODULE=schemas  # Show specific module version
    vars:
      MODULE: '{{.MODULE | default ""}}'
    preconditions:
      - sh: command -v yq >/dev/null 2>&1
        msg: "yq is required. Install: brew install yq"
    cmds:
      - |
        if [ -n "{{.MODULE}}" ]; then
          VERSION=$(yq '.{{.MODULE}}' {{.VERSION_FILE}})
          echo "{{.MODULE}}: $VERSION"
        else
          echo "Catalog Module Versions"
          echo "======================="
          yq '.' {{.VERSION_FILE}}
        fi

  version:bump:
    desc: Bump module version (MODULE required, TYPE=patch/minor/major)
    summary: |
      Bump the version for a specific catalog module following SemVer.

      Usage:
        task version:bump MODULE=schemas              # Bump patch (default)
        task version:bump MODULE=schemas TYPE=patch   # v0.1.0 -> v0.1.1
        task version:bump MODULE=schemas TYPE=minor   # v0.1.0 -> v0.2.0
        task version:bump MODULE=schemas TYPE=major   # v0.1.0 -> v1.0.0
    vars:
      MODULE: '{{.MODULE | default ""}}'
      TYPE: '{{.TYPE | default "patch"}}'
    preconditions:
      - sh: '[ -n "{{.MODULE}}" ]'
        msg: "MODULE is required. Usage: task version:bump MODULE=schemas TYPE=patch"
      - sh: command -v yq >/dev/null 2>&1
        msg: "yq is required. Install: brew install yq"
    cmds:
      - |
        CURRENT=$(yq '.{{.MODULE}}' {{.VERSION_FILE}} | sed 's/^v//')
        
        if [ "$CURRENT" = "null" ]; then
          echo "Error: Module '{{.MODULE}}' not found in {{.VERSION_FILE}}"
          exit 1
        fi
        
        IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT"
        
        case "{{.TYPE}}" in
          major)
            MAJOR=$((MAJOR + 1))
            MINOR=0
            PATCH=0
            ;;
          minor)
            MINOR=$((MINOR + 1))
            PATCH=0
            ;;
          patch)
            PATCH=$((PATCH + 1))
            ;;
          *)
            echo "Invalid TYPE: {{.TYPE}}. Use patch, minor, or major."
            exit 1
            ;;
        esac
        
        NEW="v${MAJOR}.${MINOR}.${PATCH}"
        yq -i '.{{.MODULE}} = "'$NEW'"' {{.VERSION_FILE}}
        echo "Bumped {{.MODULE}}: v${CURRENT} -> ${NEW}"

  # ============================================================================
  # Publishing
  # ============================================================================

  publish:local:
    desc: Publish module to local registry (MODULE required)
    summary: |
      Publish a specific catalog module to the local OCI registry.

      Usage:
        task publish:local MODULE=schemas              # Use version from versions.yml
        task publish:local MODULE=schemas VERSION=v0.2.0  # Use explicit version
    vars:
      MODULE: '{{.MODULE | default ""}}'
      VERSION: '{{.VERSION | default ""}}'
    preconditions:
      - sh: '[ -n "{{.MODULE}}" ]'
        msg: "MODULE is required. Usage: task publish:local MODULE=schemas"
      - sh: command -v yq >/dev/null 2>&1
        msg: "yq is required. Install: brew install yq"
    cmds:
      - |
        if [ -z "{{.VERSION}}" ]; then
          VERSION=$(yq '.{{.MODULE}}' {{.VERSION_FILE}})
        else
          VERSION="{{.VERSION}}"
        fi
        
        if [ "$VERSION" = "null" ]; then
          echo "Error: Module '{{.MODULE}}' not found in {{.VERSION_FILE}}"
          exit 1
        fi
        
        echo "Publishing {{.MODULE}}@$VERSION to {{.LOCAL_REGISTRY}}..."
        cd "{{.V0_DIR}}/{{.MODULE}}" && CUE_REGISTRY={{.LOCAL_REGISTRY}}+insecure cue mod publish "$VERSION"
        echo "Published {{.MODULE}}@$VERSION"

  publish:all:local:
    desc: Publish all modules to local registry (dependency order)
    summary: |
      Publish all catalog modules to the local OCI registry in dependency order.

      Usage:
        task publish:all:local
    preconditions:
      - sh: command -v yq >/dev/null 2>&1
        msg: "yq is required. Install: brew install yq"
    cmds:
      - |
        echo "Publishing all catalog modules to local registry..."
        echo ""
        
        {{range $mod := .CATALOG_MODULES}}{{if $mod.enabled}}
        VERSION=$(yq '.{{$mod.name}}' {{$.VERSION_FILE}})
        echo "Publishing {{$mod.name}}@$VERSION..."
        
        if (cd "{{$.V0_DIR}}/{{$mod.path}}" && \
            CUE_REGISTRY={{$.LOCAL_REGISTRY}}+insecure cue mod publish "$VERSION" 2>&1); then
          echo "  Published {{$mod.name}}@$VERSION"
        else
          echo "  Failed to publish {{$mod.name}}"
          exit 1
        fi
        echo ""
        {{end}}{{end}}
        
        echo "All catalog modules published to {{.LOCAL_REGISTRY}}"
